language: python
python:
  - "2.7"
  - "3.6"
branches:
      only:
              - master
    
# command to install dependencies
install: "pip install -r requirements_ci.txt"
# command to run tests
script: python 01_flash_leds_3x3.py
